/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jiakesiws_minipika_framework_util_Objects */

#ifndef _Included_org_jiakesiws_minipika_framework_util_Objects
#define _Included_org_jiakesiws_minipika_framework_util_Objects
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jiakesiws_minipika_framework_util_Objects
 * Method:    sizeof
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_jiakesiws_minipika_framework_util_Objects_sizeof
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
